fix: DWaterProgress not displayed text when initialized to 0
linuxdeepin/dtkwidget pull request #125
Opened 2022-07-14 09:39 UTC by justforlxz

The default value is 0. In setValue function, the text content will not be updated because the value is equal.

Issue: https://github.com/linuxdeepin/developer-center/issues/3292
Log: 修复 DWaterProgress 进度初始化为 0 时文字不显示

依赖 https://github.com/linuxdeepin/dtkcommon/pull/13

2022-07-18 09:22 UTC, zccrs requested changes

2022-07-18 09:22 UTC, zccrs commented on tests/tests.pro
> +CONFIG += c++17
我们还没有确定要把最低改为c++17，先按c++11的环境来修复这个问题

2022-07-19 02:21 UTC, zccrs commented
/+1

2022-07-22 07:46 UTC, kegechen commented
I have read the CLA Document and I hereby sign the CLA

2022-07-22 08:03 UTC, kegechen submitted a review, later dismissed

2022-07-22 08:26 UTC, merged