fix: crashed when DListView drag item with Action
linuxdeepin/dtkwidget pull request #130
Opened 2022-07-21 01:36 UTC by 18202781743

DStandardItem's `setActionList` can't be used with drag because of
Type doesn't support metatype's save and load.
  and DStandardItem doesn't release it's Action when destruction,
we use sharedpointer to manager action's life.
  Add clone override function to support that action can be access
after draged, and it need to setItemPrototype by model.

Log: 含有Action项的DListView拖动时程序崩溃
Influence: none
Change-Id: Idc489b94f4cf95850fe00a9ac8231fed80913a79

2022-07-22 07:15 UTC, kegechen commented on src/widgets/dstyleditemdelegate.cpp
> +    // TODO 不释放action，action生命周期由创建者管理，在拖动过程中，DStandardItem会被释放再重新构建
action没有和item相同的生命周期， 有点奇怪。

2022-07-27 07:05 UTC, 18202781743 commented on src/widgets/dstyleditemdelegate.cpp
> +    // TODO 不释放action，action生命周期由创建者管理，在拖动过程中，DStandardItem会被释放再重新构建
改为了，采用智能指针去管理action的生命周期

2022-07-28 01:49 UTC, zccrs requested changes

2022-07-28 01:49 UTC, zccrs commented on src/widgets/dstyleditemdelegate.cpp
> +    bool isValid() const
inline

2022-07-28 01:49 UTC, zccrs commented on src/widgets/dstyleditemdelegate.cpp
> +    const ActionListData* constData() const
inline

2022-07-28 01:49 UTC, zccrs commented on src/widgets/dstyleditemdelegate.cpp
> +    QMetaType::registerStreamOperators(QMetaTypeId<DTK_WIDGET_NAMESPACE::ActionList>::qt_metatype_id(),
加两条单元测试试一下数据的销毁和复用有没有问题

2022-07-28 07:34 UTC, zccrs approved these changes

2022-07-28 09:30 UTC, 18202781743 commented
/merge

2022-07-28 09:38 UTC, 18202781743 commented
/check

2022-07-29 00:33 UTC, 18202781743 commented
/merge

2022-07-29 00:34 UTC, merged