fix: 双击标记框内标记后面追加文字
linuxdeepin/dtkwidget pull request #132
Opened 2022-07-22 06:03 UTC by FeiW-UT003691

当光标在内容末尾且鼠标双击位置在光标右边时，
编辑返回false，不再编辑追加文字。

Log: 修复双击标记框内标记后面追加文字问题
Bug: https://pms.uniontech.com/bug-view-139561.html
Influence: 标记框
Change-Id: Ia582ebf7f40b8180352bfdfec09ac5f615047212

2022-07-22 07:31 UTC, kegechen requested changes
这个提交没有更新到最新的吧。。

2022-07-23 03:24 UTC, FeiW-UT003691 commented
> 更新done

2022-07-23 03:26 UTC, FeiW-UT003691 commented
> 这个提交没有更新到最新的吧。。

更新done

2022-07-29 06:37 UTC, kegechen approved these changes

2022-07-29 06:37 UTC, kegechen requested changes
两个提交处理一下。。

2022-07-29 07:42 UTC, kegechen approved these changes

2022-07-29 07:42 UTC, merged