BREAKING CHANGE: fold struct is changed , all pro be removed
linuxdeepin/dtkwidget pull request #138
Opened 2022-07-26 02:53 UTC by Decodetalkers

refactor(file struct): change the filefold struct

1. all to cmake
2. change examples to lib/libdtk-{version}/examples

LOG: Change the fold struct, move headers to include
influence: qmake cannot be used

2022-07-28 05:54 UTC, Decodetalkers commented
I have read the CLA Document and I hereby sign the CLA.

2022-07-28 07:50 UTC, zccrs requested changes
有一些通用问题：

1. 有一个提交在专门处理编译的warnings，但是又删除了一些 pri 文件，把那些与qmake换成cmake无关的改动拆分到一个新的PR里提交，这个代码改动本身就很多，再加一些无关的提交就会很难审核。
2.从qmake替换为cmake不应该改变项目的行为，比如一些头文件的路径，不知道为什么要改变，另外是之前一些在编译期自动生成的文件也不应该继续保持自动生成。

理想情况下，这个提交应该只删除部分 pro 和 pri 文件，添加一些 .cmake 和 CMakeLists.txt，且编译出的deb包的内容没有变化。

2022-07-28 07:50 UTC, zccrs commented on archlinux/PKGBUILD
> -depends=('deepin-qt-dbus-factory-git' 'dtkcore-git' 'dtkgui-git' 'librsvg' 'qt5-multimedia' 'qt5-svg'
为什么都改成了非 -git 的版本？

2022-07-28 07:50 UTC, zccrs commented on archlinux/PKGBUILD
> +		../
这个缩进感觉好奇怪

2022-07-28 07:50 UTC, zccrs commented on debian/dtkwidget5-examples.install
> -usr/lib/*/examples/*
这个是需要改的吗？

2022-07-28 07:50 UTC, zccrs commented on debian/libdtkwidget-dev.install
> -usr/lib/*/pkgconfig/*.pc
要同时提供 pkgconfig cmake qmake 的支持，只是把项目自身的构建系统换成 cmake，对外提供的还是要都支持。

2022-07-28 07:50 UTC, zccrs commented on debian/libdtkwidget-dev.install
> -usr/lib/*/qt5/*
同上

2022-07-28 07:50 UTC, zccrs commented on debian/libdtkwidget5.install
> -usr/lib/*/lib*.so.*
这个修改是为什么？

2022-07-28 07:50 UTC, zccrs commented on debian/libdtkwidget5.install.i386
> -usr/lib/*/lib*.so.*
同上

2022-07-28 07:50 UTC, zccrs commented on debian/rules
> +VERSION = $(DEB_VERSION_UPSTREAM)
这个文件的改动应该跟前几天合入的一个提交冲突了

2022-07-28 07:50 UTC, zccrs commented on debian/rules
> +	dh_auto_configure -- -DNOTPACKAGE=OFF
这个选项是控制什么的？

2022-07-28 07:50 UTC, zccrs commented on debian/symbols.amd64
> -libdtkwidget.so.5 libdtkwidget5 #MINVER#
这个文件为什么删掉了？

2022-07-28 07:50 UTC, zccrs commented on examples/dwidget-examples/collections/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
11

2022-07-28 07:50 UTC, zccrs commented on examples/dwidget-examples/collections/CMakeLists.txt
> +  ../../../include/dtkwidget/DWidget/
不要用这样的相对路径，可以用CMAKE变量作为前缀，用一个绝对路径，比如 ${XXXXXXXX}/include/dtkwidget/DWidget/

2022-07-28 07:50 UTC, zccrs commented on examples/dwidget-examples/collections/images.qrc
> +<!DOCTYPE RCC>
这些跟本次提交没有关系的改动不要放到这个pr里

2022-07-28 07:50 UTC, zccrs commented on examples/dwidget-examples/collections/mainwindow.cpp
> +                        painter.translate(-this->width() / 2.0, - this->height() / 2.0);
同上

2022-07-28 07:50 UTC, zccrs commented on examples/dwidget-examples/collections/mainwindow.h
> +#include "dmainwindow.h"
同上

2022-07-28 07:50 UTC, zccrs commented on examples/dwidget-examples/collections/resources.qrc
> +<!DOCTYPE RCC>
同上

2022-07-28 07:50 UTC, zccrs commented on include/dtkwidget/DWidget/DtkWidgets
> +#ifndef DTK_WIDGET_MODULE_H
这个文件是自动生成的，不要放到代码仓库里

2022-07-28 07:50 UTC, zccrs commented on include/dtkwidget/DWidget/DtkWidgets
> +#ifndef DTK_WIDGET_MODULE_H
而且上面的那些 src/widgets/DXXXXX 的头文件为什么要重命名到 include/dtkwidget/DWidget?

2022-07-28 07:50 UTC, zccrs commented on include/dtkwidget/global/dtkwidget_config.h
> +// it is auto make config
同上

2022-07-28 07:50 UTC, zccrs commented on include/dtkwidget/widgets/dbuttonbox.h
> +    QSize sizeHint() const override;
与这个提交没有关系的改动不要带进来

2022-07-28 07:50 UTC, zccrs commented on include/dtkwidget/widgets/dprintpickcolorwidget.h
> +    DPrintPickColorWidget(QWidget *parent = nullptr);
同上，其他类似的地方就不一一指出了

2022-07-28 07:50 UTC, zccrs commented on misc/cmake/DtkWidgetConfig.cmake
> +find_package(Dtk REQUIRED Core)
这应该自动生成呀

2022-07-28 07:50 UTC, zccrs commented on plugin/dtkuidemo/CMakeLists.txt
> +  ../../../include/dtkwidget/DWidget/
不要使用这种相对目录，定义一个cmake变量来代替，前面也有一个类似的地方，其他类似的问题就不一一指出了

2022-07-28 07:50 UTC, zccrs commented on src/util/daccessibilitychecker.cpp
> +#include "dtkwidget/util/daccessibilitychecker.h"
不应该做这样的改动

2022-07-28 07:50 UTC, zccrs commented on src/widgets/dabstractdialog.cpp
> +//#include "danchors.h"
？？

2022-07-28 07:50 UTC, BLumia commented
得先 rebase 一下吧，不然和现有的文档生成放的 CMakeLists 配置是肯定冲突的

2022-07-28 07:52 UTC, Decodetalkers commented on src/widgets/dabstractdialog.cpp
> +//#include "danchors.h"
这个是clangd警告的，警告说这个是没有使用的，所以我顺便去掉了

2022-07-28 07:53 UTC, zccrs commented
为什么不是先从改 dtkcommon dtkcore 项目开始呢，怎么直接就改dtkwidget了

2022-07-28 07:54 UTC, Decodetalkers commented on debian/dtkwidget5-examples.install
> -usr/lib/*/examples/*
更改了安装的路径，当前的example放在了/usr/lib/example下，这个/usr/lib/example没有标志属于任何项目，所以我把它移动到了/usr/lib/libdtk/Dtkwidget/example下

2022-07-28 07:54 UTC, Decodetalkers commented on archlinux/PKGBUILD
> -depends=('deepin-qt-dbus-factory-git' 'dtkcore-git' 'dtkgui-git' 'librsvg' 'qt5-multimedia' 'qt5-svg'
我会改回去的。。这个是本地生成测试了下，。。

2022-07-28 07:56 UTC, Decodetalkers commented on include/dtkwidget/DWidget/DtkWidgets
> +#ifndef DTK_WIDGET_MODULE_H
因为方便进行通配和阅读和打包，所以把头文件单独放在include下了

2022-07-28 07:57 UTC, Decodetalkers commented on plugin/dtkuidemo/CMakeLists.txt
> +  ../../../include/dtkwidget/DWidget/
这个是项目里面的demo,demo使用自己项目里面的头文件，所以直接使用相对路径了

2022-07-28 07:57 UTC, Decodetalkers commented on src/util/daccessibilitychecker.cpp
> +#include "dtkwidget/util/daccessibilitychecker.h"
这个是和dtkcore下的头文件冲突了，如果需要把头文件单独拿出来，那得最完整的路径

2022-07-28 08:06 UTC, Decodetalkers commented
> 为什么不是先从改 dtkcommon dtkcore 项目开始呢，怎么直接就改dtkwidget了

Core已经是Cmake了，common只是相关工具，改用cmake后就不需要了

2022-07-28 08:23 UTC, zccrs commented
> 

dtkcore 现在的 CMakeLists.txt 只是生成文档用的。项目自身还是 qmake。另外，即便改成cmake，dtkcommon还是需要的，它的定位是提供一些通用的构建期方法，比如为所有dtk模块提供统一的项目结构，提供生成 pkgconfig qmake 模块的函数等等。从qmake改成cmake也需要提供同样的东西，所以这个项目还是需要的。

2022-08-17 07:57 UTC, kegechen commented
重复提交留一个

2022-08-17 07:57 UTC, closed without merging