feat(tocmake): tocmake
linuxdeepin/dtkwidget pull request #141
Opened 2022-07-29 09:20 UTC by Decodetalkers

Log: tocmake

2022-07-29 09:26 UTC, Decodetalkers commented
项目中
modified:   daboutdialog.cpp
 modified:   dapplication.cpp
modified:   dbuttonbox.cpp
modified:   dfloatingbutton.cpp
modified:   dfloatingmessage.cpp
modified:   dmessagemanager.cpp
 modified:   dstyle.cpp
modified:   dstyleditemdelegate.cpp

包含v23的改动，编译不通过，所以我暂时改回没有使用23函数的版本，不然我不知道是否可以编译成功

2022-08-01 00:43 UTC, kegechen commented
> 项目中 modified: daboutdialog.cpp modified: dapplication.cpp modified: dbuttonbox.cpp modified: dfloatingbutton.cpp modified: dfloatingmessage.cpp modified: dmessagemanager.cpp modified: dstyle.cpp modified: dstyleditemdelegate.cpp
> 
> 包含v23的改动，编译不通过，所以我暂时改回没有使用23函数的版本，不然我不知道是否可以编译成功

不行的，master分支是开发分支，你这个合并也是提价到master分支，相当于把功能移除了。你可以本地配置dtkcore/dtkgui的开发环境

2022-08-02 02:11 UTC, kegechen requested changes
1. 目录结构可以改，但是不要尽量不要改动代码，将代码中的改动作为单独提交
2. 提交前先 rebase，部分代码不是最新的，比如main.cpp (涉及到代码变动的参考1)
3.  原来qmake/cmake/pkg-config支持的不能少
4. 尽量从dtkcommon/dtkcore/dtkgui 开始

2022-08-09 09:41 UTC, Decodetalkers commented
/check

2022-08-10 01:14 UTC, Decodetalkers commented
/check

2022-08-18 06:03 UTC, kegechen commented on CMakeLists.txt
> +
多余空行

2022-08-18 06:05 UTC, kegechen commented on CMakeLists.txt
> +endif()
是不是可以简化为
option(DVERSION "define project version" "5.5.22")

if(DVERSION STREQUAL "OFF")
    set(DVERSION "5.5.22")
endif()

 project (DtkWidget
    VERSION ${DVERSION}
    DESCRIPTION "DTK Widget module"
    HOMEPAGE_URL "https://github.com/linuxdeepin/dtkwidget"
    LANGUAGES CXX C
  )

2022-08-18 06:06 UTC, kegechen commented on CMakeLists.txt
> +    DESCRIPTION "DTK Core module"
DTK Widget module

2022-08-18 06:07 UTC, kegechen commented on CMakeLists.txt
> +option(NOTPACKAGE "to make package" ON)
是否可以命名为 BUILD_TESTS ，本意也是不编 test

2022-08-18 06:09 UTC, kegechen requested changes
多余的空行，没必要的注释可以清理一下。

2022-08-19 05:12 UTC, Decodetalkers commented
/check debian-build

2022-08-19 05:20 UTC, kegechen commented on CMakeLists.txt
> +    DESCRIPTION "DTK Core module"
@Decodetalkers

2022-08-19 06:45 UTC, Decodetalkers commented
/check debian-build

2022-08-19 08:58 UTC, Decodetalkers commented
/check debian-build

2022-08-19 09:18 UTC, kegechen approved these changes

2022-08-19 09:18 UTC, merged