feat: Enable DListView and DViewItemAction to support DciIcon
linuxdeepin/dtkwidget pull request #144
Opened 2022-08-02 02:35 UTC by cccccccb

1. Add an interface to set the DCI icon in DListView.
2. Add drawing support for DCI icon in DStyledItemtDelegate.

Log:
Influence: None
Change-Id: If4ed076e8c2a819b28e5d046f885a22b6c0b8272

2022-08-02 06:16 UTC, cccccccb commented
/review @zccrs @kegechen

2022-08-02 06:20 UTC, cccccccb commented
/review @kegechen
/review @18202781743

2022-08-03 08:38 UTC, kegechen submitted a review, later dismissed

2022-08-03 08:43 UTC, 18202781743 commented on src/widgets/dstyleditemdelegate.h
> +DGUI_END_NAMESPACE
这个是不是没必要了，已经必须包含头文件了，

2022-08-03 08:51 UTC, 18202781743 commented
/+1

2022-08-03 09:36 UTC, cccccccb commented on src/widgets/dstyleditemdelegate.h
> +DGUI_END_NAMESPACE
已修改

2022-08-05 02:11 UTC, zccrs requested changes

2022-08-05 02:11 UTC, zccrs commented on src/widgets/dstyleditemdelegate.cpp
> +        if (opt.icon.isNull()) {
应该优先用 dciIcon, if (d->dciIcon.isNull()) {...} else {...}

2022-08-05 02:11 UTC, zccrs commented on src/widgets/dstyleditemdelegate.cpp
> +static void saveDDciIconVariant(QDataStream &s, const void *d)
这种支持是不是能直接放到 DDciIcon 类的实现里，另外还有对 QVariant 的支持，可以试试。避免以后有其它需要的地方也得自己实现。

2022-08-09 09:41 UTC, cccccccb commented on src/widgets/dstyleditemdelegate.cpp
> +        if (opt.icon.isNull()) {
opt.icon.isNull() 这个应该就是 dciIcon 了呀 HasDecoration 这会存在 dciicon 和 qticon ，优先使用 dciicon（qticon 为空则表示 dci icon有数据）

2022-08-09 09:43 UTC, zccrs commented on src/widgets/dstyleditemdelegate.cpp
> +        if (opt.icon.isNull()) {
不一样呀，如果 icon 和 dciIcon 同时不是空呢，那不就不会使用 dciIcon 了？

2022-08-09 09:45 UTC, cccccccb commented on src/widgets/dstyleditemdelegate.cpp
> +static void saveDDciIconVariant(QDataStream &s, const void *d)
QVariant 的支持的意思是注册元类型吗 DDciIcon 里面已经加了 Q_DECLARE_METATYPE 这个宏  saveDDciIconVariant 函数是方便  DDciIcon 在 QVariant 中的读写操作，应该可以挪到 DDciIcon 里面实现

2022-08-09 09:57 UTC, cccccccb commented on src/widgets/dstyleditemdelegate.cpp
> +static void saveDDciIconVariant(QDataStream &s, const void *d)
不过感觉无论是放到 使用方 还是 原始类 里面调用 qRegisterMetaTypeStreamOperators 函数声明流运算的操作函数都听奇怪的，原始类里面对于那些不使用的地方这些操作是多余的 :( 
https://www.qt.io/blog/whats-new-in-qmetatype-qvariant Qt 6已经删除了 qRegisterMetaTypeStreamOperators 函数，也就是说应该不需要手动添加 qRegisterMetaTypeStreamOperators 这种流运算函数了。
我们目前的做法可以先在 DDciIcon 中添加这些流函数进行过渡

2022-08-09 10:12 UTC, cccccccb commented on src/widgets/dstyleditemdelegate.cpp
> +        if (opt.icon.isNull()) {
噢噢

2022-08-10 01:53 UTC, zccrs commented on src/widgets/dstyleditemdelegate.cpp
> +static void saveDDciIconVariant(QDataStream &s, const void *d)
嗯，参考Qt的推荐做法，在最合适的地方加。

2022-08-10 06:32 UTC, cccccccb commented
/check check_job

2022-08-10 06:33 UTC, cccccccb commented
/check apicheck

2022-08-11 03:22 UTC, cccccccb commented on src/widgets/dstyleditemdelegate.cpp
> +static void saveDDciIconVariant(QDataStream &s, const void *d)
已在 dtkgui 中增加合入相应 DDciIcon 的类型注册，dtkwidget测试未发现问题

2022-08-11 03:49 UTC, zccrs approved these changes

2022-08-11 03:54 UTC, cccccccb commented
/merge

2022-08-11 05:06 UTC, cccccccb commented
/merge

2022-08-11 05:06 UTC, merged