fix: shotcuts show in context menu
linuxdeepin/dtkwidget pull request #207
Opened 2022-11-02 01:25 UTC by kegechen

Don't show shortcuts in context menu
QDeepinTheme::themeHint(ShowShortcutsInContextMenus) return false not work anymore
see https://codereview.qt-project.org/c/qt/qtbase/+/351295

Bug: https://pms.uniontech.com/bug-view-167667.html
Log: Don't Show Shortcuts In Context Menus
Change-Id: Ifc08b39d9b4b6b15d66c3e07fd41443b93d48b27

2022-11-02 08:49 UTC, zccrs requested changes

2022-11-02 08:49 UTC, zccrs commented on src/widgets/dapplication.cpp
> +    if (QLatin1String("FALSE") != qgetenv("DTK_DontShowShortcutsInContextMenus").toUpper())
qEnvironmentVariableIsSet("D_DTK_XXXXXXX")

环境变量要全大写，另外参考下其它已有的环境变量，应该都是 “D_DTK_”开头。另外不要用 != false 这种判断，太宽泛了，尽量用 == XXXX 来判断，让判断条件执行下去的标志更明显一些，而且如果要用true false判断，也应该同时支持 0 1 这种值，一般后者可能用的多一些。对于这个功能我建议直接判断某个环境变量有没有设置，不用管值是啥。

2022-11-02 08:53 UTC, kegechen commented on src/widgets/dapplication.cpp
> +    if (QLatin1String("FALSE") != qgetenv("DTK_DontShowShortcutsInContextMenus").toUpper())
这里是想默认设置这个不显示快捷方式，除非想显示快捷方式才用环境变量

2022-11-04 02:59 UTC, zccrs approved these changes

2022-11-04 06:05 UTC, kegechen commented
在平台插件中修改更合适。

2022-11-04 06:05 UTC, closed without merging

2022-11-04 06:15 UTC, kegechen commented
https://github.com/linuxdeepin/qt5platform-plugins/pull/148