feat: Add TightMode support
linuxdeepin/dtkwidget pull request #289
Opened 2022-12-26 10:03 UTC by 18202781743

Send SizeModeEvent for all widget when received sizemode
changed.
  Add SizeModeHelper for common function.

Log: 支持紧凑模式切换
Task: https://pms.uniontech.com/task-view-227385.html
Influence: none
Change-Id: I3cb83d22db1b3b058ed34443263d8321af09281d

2022-12-27 02:36 UTC, zccrs requested changes

2022-12-27 02:36 UTC, zccrs commented on include/dtkwidget/util/dsizemode.h
> +    static QEvent::Type Type;
是不是直接定义到cpp里就行了

2022-12-27 02:36 UTC, zccrs commented on include/dtkwidget/util/dsizemode.h
> +    int mode;
mode不是个枚举吗

2022-12-27 02:36 UTC, zccrs commented on src/widgets/dapplication.cpp
> +    for (auto iter = widgets.rbegin(); iter != widgets.rend(); iter++) {
可以直接就在上面的while循环中发送事件，不用搞两遍循环

2022-12-27 02:36 UTC, zccrs commented on include/dtkwidget/util/dsizemode.h
> +    static QEvent::Type Type;
留出一个 static 函数给外部访问，直接让他访问变量会导致它有可能被意外修改

2022-12-27 02:36 UTC, zccrs commented on src/widgets/dapplication.cpp
> +    DSizeModeEvent ev(DGuiApplicationHelper::instance()->sizeMode());
这个世界的名字是不是叫 DSizeModeChangeEvent 会更合适

2022-12-27 02:36 UTC, zccrs commented on src/widgets/dtitlebar.cpp
> +    const int DefaultTitlebarHeight = 40;
可以加上一个 static ，不然可能会在二进制里产生符号。

2022-12-27 02:36 UTC, zccrs commented on src/widgets/dapplication.cpp
> +    connect(DGuiApplicationHelper::instance(), SIGNAL(sizeModeChanged(DGuiApplicationHelper::SizeMode)),
DGuiApplicationHelper里的sizeModeChanged是之前就有了？

2022-12-27 04:28 UTC, 18202781743 commented on src/widgets/dapplication.cpp
> +    connect(DGuiApplicationHelper::instance(), SIGNAL(sizeModeChanged(DGuiApplicationHelper::SizeMode)),
是这个需求里dtkgui里提交的，

2022-12-27 04:29 UTC, 18202781743 commented on src/widgets/dapplication.cpp
> +    for (auto iter = widgets.rbegin(); iter != widgets.rend(); iter++) {
这里想倒序遍历，上面的一个while循环搞不定吧，

2022-12-27 04:31 UTC, 18202781743 commented on include/dtkwidget/util/dsizemode.h
> +    static QEvent::Type Type;
加个const行不，主要是为了访问稍微方便点儿，DSizeModeChangeEvent::Type，类似QEvent::Timer这样的写法，

2022-12-27 05:56 UTC, kegechen commented on src/widgets/dtitlebar.cpp
> +        q->setMinimumHeight(DSizeModeHelper::element(tight::DefaultTitlebarHeight, DefaultTitlebarHeight, tight));
这么多是不是可以只更新一下 DefaultTitlebarHeight，DefaultExpandButtonSize，DefaultIconHeight 的值就可以，不需要重复计算那么多次，虽然没有什么计算量

2022-12-28 00:48 UTC, 18202781743 commented on src/widgets/dtitlebar.cpp
> +        q->setMinimumHeight(DSizeModeHelper::element(tight::DefaultTitlebarHeight, DefaultTitlebarHeight, tight));
感觉不用改，现在只是几个size恰好取的是同样的值而已，只是为了方便理解，另外它是个inline函数，

2022-12-28 07:30 UTC, xzl01 commented on docs/widgets/dsizemode.zh_CN.dox
> +@sa DGUI_NAMESPACE::DGuiApplicationHelper::SizeMode
doxygen它不认宏命名空间

2022-12-28 07:30 UTC, xzl01 commented on docs/widgets/dsizemode.zh_CN.dox
> +@property DGUI_NAMESPACE::DGuiApplicationHelper::SizeMode DSizeModeChangeEvent::mode
同上

2022-12-29 07:47 UTC, zccrs commented on include/dtkwidget/util/dsizemode.h
> +    static QEvent::Type Type;
QEvent::Timer 是个枚举呀，在Qt的设计原则里，一般不会允许直接操作类的成员变量

2022-12-29 07:48 UTC, zccrs commented on src/widgets/dapplication.cpp
> +    for (auto iter = widgets.rbegin(); iter != widgets.rend(); iter++) {
通知的顺序有什么特别的意义吗

2022-12-29 08:50 UTC, 18202781743 commented on src/widgets/dapplication.cpp
> +    for (auto iter = widgets.rbegin(); iter != widgets.rend(); iter++) {
需要子控件先处理自己的size，否则布局可能出现问题，

2022-12-29 08:52 UTC, 18202781743 commented on include/dtkwidget/util/dsizemode.h
> +    static QEvent::Type Type;
如果我想要判断dsizemodechangeevent的类型，还是需要定义一个常量，给外部判断，

2022-12-30 01:59 UTC, zccrs commented on include/dtkwidget/util/dsizemode.h
> +    static QEvent::Type Type;
在 DSizeModeChangeEvent 里提供一个

````cpp
static QEvent::Type type();
````
的静态函数，把 static QEvent::Type Type 这个静态变量移动到 cpp 文件里定义，不要放到这个类里了。甚至可以直接在 static QEvent::Type DSizeModeChangeEvent::type() 函数里定义。

2022-12-30 02:07 UTC, zccrs commented on src/widgets/dapplication.cpp
> +    for (auto iter = widgets.rbegin(); iter != widgets.rend(); iter++) {
这种一般用函数递归就行了。Qt里做类似的操作时也是这样的。

2022-12-30 05:56 UTC, zccrs commented on include/dtkwidget/util/dsizemode.h
> +    static inline bool enabled()
这个函数会用在什么地方，只用 isCompactMode 不就够了吗

2022-12-30 07:11 UTC, 18202781743 commented on include/dtkwidget/util/dsizemode.h
> +    static inline bool enabled()
在有的typedef的dtkwidget控件，例如DPushButton，需要安装一个过滤器去处理SizeModeChangeEvent事件，希望加个判断，只有开启了SizeMode的支持后，才去加这个过滤器

2022-12-30 07:20 UTC, zccrs requested changes

2022-12-30 07:20 UTC, zccrs commented on include/dtkwidget/util/dsizemode.h
> +    static inline bool enabled()
但是 DGUI_NAMESPACE::DGuiApplicationHelper::instance()->sizeMode() 应该不会有值为 InvalidMode 的可能性，除非是通过环境变量指定的？
控制中心的设置不会产生 InvalidMode，DGuiApplicationHelper::setSizeMode 也不会，因为如果这里设置为 InvalidMode，那意味着reset到系统设置。

2022-12-30 09:09 UTC, 18202781743 commented on include/dtkwidget/util/dsizemode.h
> +    static inline bool enabled()
确实有这个bug，这个enable我再看看吧，先移除掉，
之后在gui里的提供新的接口支持之后再看要不要加上，

2023-01-06 05:01 UTC, 18202781743 commented
/check

2023-01-06 08:54 UTC, 18202781743 commented
/check build

2023-01-09 02:11 UTC, zccrs commented on docs/widgets/dsizemode.zh_CN.dox
> +@param[in] compact 是否为紧凑模式
这个函数的必要性有多大呢，如果需要传入 compact 值，那在使用的地方直接 `compact ? 1 : 2` 这样不是更方便吗

2023-01-09 02:13 UTC, zccrs commented on include/dtkwidget/util/dsizemode.h
> +    static inline QSize iconSize(const int s1, const int s2)
专门搞一个 iconSize 函数的必要性是什么？直接用 element 不是一样的效果吗，从 element 的定位看它就是一个通用的。

2023-01-09 02:13 UTC, zccrs commented on include/dtkwidget/widgets/dmainwindow.h
> +    bool event(QEvent *event) Q_DECL_OVERRIDE;
直接用 override，Qt也在去 Q_DECL_OVERRIDE 化

2023-01-09 02:14 UTC, zccrs commented on src/util/dsizemode.cpp
> +// SPDX-FileCopyrightText: 2020 - 2022 UnionTech Software Technology Co., Ltd.
年份错了

2023-01-09 02:14 UTC, zccrs commented on src/util/util.cmake
> +  ${CMAKE_CURRENT_LIST_DIR}/dsizemode.cpp
这个cpp是空的吧，不需要的话可以不用创建

2023-01-09 02:16 UTC, zccrs commented on src/widgets/dapplication.cpp
> +    connect(DGuiApplicationHelper::instance(), SIGNAL(sizeModeChanged(DGuiApplicationHelper::SizeMode)),
确认一下SIGNAL里的函数签名是不是需要加上命名空间

2023-01-09 02:18 UTC, zccrs commented on src/widgets/dtitlebar.cpp
> +            optionButton->setIconSize(DSizeModeHelper::iconSize(compact::DefaultTitlebarHeight, DefaultTitlebarHeight, compact));
为什么不用两个参数的版本呢，而是自己指定 compact？

2023-01-09 02:20 UTC, zccrs commented on src/widgets/private/dapplication_p.h
> +#include "dsizemode.h"
往上放，属于当前项目的头文件则放到最前面的区域。

2023-01-09 03:59 UTC, 18202781743 commented on src/widgets/dapplication.cpp
> +    connect(DGuiApplicationHelper::instance(), SIGNAL(sizeModeChanged(DGuiApplicationHelper::SizeMode)),
不加也没报错，跟在gui里定义的信号一致都不加名字空间就可以，

2023-01-09 05:08 UTC, zccrs requested changes

2023-01-09 05:08 UTC, zccrs commented on docs/widgets/dsizemode.zh_CN.dox
> +@breif 获取是否为紧凑模式对应的元素值
应该描述为“根据当前的 size mode 是否为紧凑模式返回对应的值”

2023-01-09 05:08 UTC, zccrs commented on docs/widgets/dsizemode.zh_CN.dox
> +@return 返回当前控件大小模式下对应模式下的元素值
文档里可以加一下 see also，推荐阅读者看一下 DGuiApplicationHelper 相关的接口

2023-01-09 06:53 UTC, zccrs approved these changes

2023-01-09 07:02 UTC, 18202781743 commented
/merge

2023-01-10 01:29 UTC, 18202781743 commented
/check

2023-01-10 03:12 UTC, merged