chore: update changelog
linuxdeepin/dtkwidget pull request #309
Opened 2023-02-06 09:25 UTC by Decodetalkers

Log: update to 5.6.6

2023-02-06 09:43 UTC, xzl01 submitted a review, later dismissed

2023-02-07 09:04 UTC, kegechen commented on debian/changelog
> +  * Release 5.6.5 update with broken dtkcore
这个。。。5.6.5 ？

2023-02-07 09:04 UTC, kegechen requested changes
写错了，改了

2023-02-13 07:46 UTC, kegechen approved these changes

2023-02-13 07:49 UTC, kegechen commented on debian/changelog
> +  * New feature: custom titlebar
这个貌似不是在 5.6.5- 5.6.6 之间引入的。不要写在里面

2023-02-13 08:15 UTC, kegechen approved these changes

2023-02-13 08:15 UTC, merged