feat: 增加覆盖指定界面的水印类DWaterMarkHelper
linuxdeepin/dtkwidget pull request #339
Opened 2023-02-24 08:06 UTC by ssk-wh

可通过DWaterMarkHelper的接口设置水印样式，并通过registerWidget添加水印

Log:
Influence: 无
Task: https://pms.uniontech.com/task-view-243575.html Change-Id: I84cf4d3fb0eb17deb0ab9c2e7b154bf884167a0b

2023-02-24 09:56 UTC, ssk-wh commented
> **Doc Check bot** yellow_circle some documents missing!
> 
> File	Line	Symbol
> include/widgets/dwatermarkhelper.h	17	Dtk::Widget::DWaterMarkHelper
> include/widgets/dwatermarkwidget.h	79	DWaterMarkWidget::DWaterMarkWidget
> include/widgets/dwatermarkwidget.h	19	WaterMarkType
> include/widgets/dwatermarkwidget.h	24	WaterMarkLayout
> include/widgets/dwatermarkwidget.h	29	WaterMarkData::WaterMarkData
> include/widgets/dwatermarkwidget.h	31	WaterMarkData::WaterMarkData
> include/widgets/dwatermarkwidget.h	32	WaterMarkData & WaterMarkData::operator=

我都添加文档了呀，为啥还是有这些

2023-02-25 05:21 UTC, xzl01 commented
> > **Doc Check bot** yellow_circle some documents missing!
> > File	Line	Symbol
> > include/widgets/dwatermarkhelper.h	17	Dtk::Widget::DWaterMarkHelper
> > include/widgets/dwatermarkwidget.h	79	DWaterMarkWidget::DWaterMarkWidget
> > include/widgets/dwatermarkwidget.h	19	WaterMarkType
> > include/widgets/dwatermarkwidget.h	24	WaterMarkLayout
> > include/widgets/dwatermarkwidget.h	29	WaterMarkData::WaterMarkData
> > include/widgets/dwatermarkwidget.h	31	WaterMarkData::WaterMarkData
> > include/widgets/dwatermarkwidget.h	32	WaterMarkData & WaterMarkData::operator=
> 
> 我都添加文档了呀，为啥还是有这些

因为它不会重复扫描

2023-02-25 05:24 UTC, xzl01 commented
确认了下，确实没有文档 @Whale107 你可以帮忙补齐下文档

2023-02-27 01:40 UTC, xzl01 requested changes
待补充文档

2023-02-27 08:42 UTC, 18202781743 commented on include/widgets/dwatermarkwidget.h
> +    bool grayScale();
添加上const修饰符，bool grayScale() const;

2023-02-27 08:49 UTC, 18202781743 commented on src/widgets/dwatermarkwidget.cpp
> +    auto pd = p.d_func();
与上面代码重复了，WaterMarkDataPrivate是不是提供一个赋值构造函数就可以了，

2023-02-27 08:50 UTC, 18202781743 commented on src/widgets/dwatermarkwidget.cpp
> +const WaterMarkData::WaterMarkType &WaterMarkData::type()
const 修饰；

2023-02-27 08:54 UTC, 18202781743 commented on src/widgets/dwatermarkwidget.cpp
> +    WaterMarkData cloneData = data;
这个变量是不是可以不用了，下面好像没有修改过它，它与data值是一致的，

2023-02-27 08:59 UTC, 18202781743 commented on src/widgets/dwatermarkwidget.cpp
> +QImage createTextureImage(const WaterMarkData &data, qreal deviceScale)
可以加上static修饰，免得可能与其它库的函数签名相同，

2023-02-27 09:04 UTC, 18202781743 commented on src/widgets/dwatermarkwidget.cpp
> +    d->textureImage = createTextureImage(d->data, devicePixelRatioF());
若它不在paint时机调用的话，内部实现的QPainter使用会不会有问题，报painter不可用，

2023-02-27 09:05 UTC, 18202781743 commented on src/widgets/dwatermarkwidget.cpp
> +    return false;
确认下需不需要调用下父类的实现，

2023-02-27 09:08 UTC, 18202781743 commented on src/widgets/dwatermarkwidget.cpp
> +        if (d->data.layout() == WaterMarkData::Center) {
这个与 drawWaterTexture()的逻辑是互斥的么，是否可以用else来进行分支，否则以后加代码可能造成提前return了，

2023-02-27 09:16 UTC, 18202781743 commented on src/widgets/dwatermarkhelper.cpp
> +        mark->setVisible(true);
mark受widget的显示隐藏控制吧，是不是可以不用显示指定mark->setVisible()为true，
mark指定了它的parent为widget，也进行了resize的同步，是不是可以不用指定resize了，

2023-02-27 09:21 UTC, 18202781743 commented on examples/collections/main.cpp
> +    auto ins = DWaterMarkHelper::instance();
这个collections示例，是经过设计的，尽量不改变它的默认显示，
这部分示例代码可以独立出来，提供一个入口调用即可，需要能够控制，注册和取消，

2023-03-01 14:52 UTC, xzl01 commented on src/widgets/dwatermarkwidget.cpp
> +  \brief 当前设置的水印布局类型
不是 就不应该注释出现在代码中

2023-03-06 08:17 UTC, xzl01 commented on docs/widgets/dwatermarkhelper.zh_CN.dox
> +@brief 不允许直接实例化此对象
这个位置用@warning更好点,有高亮提醒

2023-03-14 06:33 UTC, closed without merging

2023-03-14 06:39 UTC, ssk-wh commented on src/widgets/dwatermarkwidget.cpp
> +    auto pd = p.d_func();
记得之前没加好像有个地方会报错，我改完再确认一遍

2023-03-14 06:48 UTC, ssk-wh commented on src/widgets/dwatermarkwidget.cpp
> +    return false;
嗯，这里要改，写错了

2023-03-14 06:50 UTC, ssk-wh commented on src/widgets/dwatermarkwidget.cpp
> +        if (d->data.layout() == WaterMarkData::Center) {
可以，之前借鉴的打印预览部分，已改

2023-03-14 06:51 UTC, ssk-wh commented on src/widgets/dwatermarkhelper.cpp
> +        mark->setVisible(true);
这里resize是为了确保第一次显示时就保持一致，不能确定这个widget在调用show的时候会触发resize，所以才加了这一步

2023-03-14 06:52 UTC, ssk-wh commented on src/widgets/dwatermarkhelper.cpp
> +        mark->setVisible(true);
mark不被控制显示和隐藏状态，只要绑定了，widget显示时就会有mark，隐藏时跟着一起隐藏，应该不用动这里

2023-03-14 07:01 UTC, ssk-wh commented on docs/widgets/dwatermarkhelper.zh_CN.dox
> +@brief 不允许直接实例化此对象
文档重新搞了一遍

2023-03-14 07:02 UTC, ssk-wh commented on src/widgets/dwatermarkwidget.cpp
> +    d->textureImage = createTextureImage(d->data, devicePixelRatioF());
内部的painter是绘制到QImage上，这个会报不可用的问题么，我用的时候都是正常的呀

2023-03-14 07:49 UTC, ssk-wh commented on src/widgets/dwatermarkhelper.cpp
> +        mark->setVisible(true);
经过验证，这里可以不用使用resize,在widget show的时候会有resize事件，已去除

2023-03-14 08:06 UTC, ssk-wh commented on src/widgets/dwatermarkwidget.cpp
> +    WaterMarkData cloneData = data;
已经修改，之前是因为data的几个成员函数都不是const类型导致的

2023-03-15 01:23 UTC, 18202781743 commented on examples/collections/main.cpp
> +    auto ins = DWaterMarkHelper::instance();
示例代码还有给开发者用的作用，已经写了可以移植过去，免得以后加文档又写一遍，