chore: add dfeaturedisplaydialog image to docs
linuxdeepin/dtkwidget pull request #351
Opened 2023-03-08 06:41 UTC by FeiWang1119

add image to docs

Log: add dfeaturedisplaydialog image to docs
Influence: docs
Change-Id: Ia8db1b78e1e9da6404417b8cd9945526d71cc6a3

2023-03-09 03:08 UTC, kegechen requested changes
comimit

docs: xxxx

2023-03-10 02:22 UTC, FeiWang1119 commented
> comimit
> 
> docs: xxxx

done

2023-03-10 05:37 UTC, kegechen approved these changes

2023-03-13 01:03 UTC, xzl01 approved these changes

2023-03-13 05:27 UTC, FeiWang1119 commented
/merge

2023-03-13 05:27 UTC, merged