fix: add color-only mode in dprintpreviewdialog
linuxdeepin/dtkwidget pull request #355
Opened 2023-03-10 02:13 UTC by FeiWang1119

add support for color-only mode to dprintpreviewdialog

Log: add color-only mode in dprintpreviewdialog
Bug: https://github.com/linuxdeepin/dtkwidget/issues/354
Influence: print preview
Change-Id: I09b3e12f5add14b5a2d323a2a6251f724a21089d

2023-03-10 02:42 UTC, 18202781743 approved these changes

2023-03-10 05:33 UTC, kegechen reviewed
Bug ==> Issue

2023-03-10 05:37 UTC, kegechen requested changes

2023-03-10 05:37 UTC, kegechen commented on src/widgets/dprintpreviewdialog.cpp
> +            colorModeCombo->addItem(qApp->translate("DPrintPreviewDialogPrivate", "Grayscale"));
blockSignals 要放到 additem 下面吧， 就是为了这里添加时不发送信号的

2023-03-10 06:02 UTC, FeiWang1119 commented
> Bug ==> Issue

done

2023-03-10 06:03 UTC, FeiWang1119 commented on src/widgets/dprintpreviewdialog.cpp
> +            colorModeCombo->addItem(qApp->translate("DPrintPreviewDialogPrivate", "Grayscale"));
done

2023-03-13 01:48 UTC, kegechen approved these changes

2023-03-13 05:26 UTC, FeiWang1119 commented
/merge

2023-03-13 05:27 UTC, merged