fix: DAbstractDialog translucent background
linuxdeepin/dtkwidget pull request #359
Opened 2023-03-13 07:25 UTC by kegechen

if windowmanager not support blur window effect
do not set `Qt::WA_TranslucentBackground` attribute setblurEnabled will not work

Issue: https://github.com/linuxdeepin/dtkwidget/issues/358
Log: fix Dialog translucent background

2023-03-13 08:12 UTC, 18202781743 commented on src/widgets/dabstractdialog.cpp
> +        if (DWindowManagerHelper::instance()->hasBlurWindow())
是不是少个！呀，支持模糊的时候hasBlurWindow返回true,这个时候setBlurEnabled为false么？

2023-03-13 08:30 UTC, zccrs requested changes

2023-03-13 08:30 UTC, zccrs commented on src/widgets/dabstractdialog.cpp
> +        if (DWindowManagerHelper::instance()->hasBlurWindow())
应该是有 ！

2023-03-13 08:58 UTC, kegechen commented on src/widgets/dabstractdialog.cpp
> +        if (DWindowManagerHelper::instance()->hasBlurWindow())
确实 ！

2023-03-14 10:11 UTC, 18202781743 approved these changes

2023-03-15 06:10 UTC, merged