fix: DMPRISControl style conflicts with design
linuxdeepin/dtkwidget pull request #411
Opened 2023-04-12 07:31 UTC by asterwyx

* Icon is too small compared to design, replace the icon with new icon that is 36x36 and fix the button size (52x52) and icon size.
* Spacing between media control buttons is smaller than design. Set fixed spacing in control buttons layout (Default is 80px).
* Add DMPRISControl example in collections.

Log: fix DMPRISControl style conflicts with design

2023-04-13 01:51 UTC, zccrs reviewed
有DCI的图标吗？

2023-04-13 07:59 UTC, asterwyx commented
> 有DCI的图标吗？

让测试提供吗？

2023-04-13 08:42 UTC, zccrs commented
> > 有DCI的图标吗？
> 
> 让设计提供吗？

是的

2023-04-17 01:38 UTC, asterwyx commented
> > > 有DCI的图标吗？
> > 
> > 
> > 让设计提供吗？
> 
> 是的

已经替换成DCI图标。

2023-04-17 01:41 UTC, zccrs requested changes

2023-04-17 01:41 UTC, zccrs commented on src/widgets/dmpriscontrol.cpp
> +    m_playBtn->setIcon(QIcon::fromTheme(":/assets/images/play_start.dci"));
有了dci的就不用留着svg的了，另外，dci主题有一个规范，把文件放到特性目录后，用 DIconTheme::findDciIconFile 来查找。

2023-04-17 01:41 UTC, zccrs commented on src/widgets/dmpriscontrol.cpp
> +    m_playBtn->setIcon(QIcon::fromTheme(":/assets/images/play_start.dci"));
dtkwidget中提供的Button应该都支持了 setIcon(DDciIcon)

2023-04-18 01:48 UTC, zccrs approved these changes

2023-04-18 02:10 UTC, merged