fix: titlebar was not updated when titlebarHeight was changed
linuxdeepin/dtkwidget pull request #423
Opened 2023-04-19 07:34 UTC by chenchongbiao

修复titlebarHeight属性被修改时，标题栏没有实时生效。

issue: https://github.com/linuxdeepin/dtk/issues/51

2023-04-19 08:08 UTC, chenchongbiao commented
/review @18202781743

2023-04-19 08:22 UTC, 18202781743 commented on src/widgets/dtitlebar.cpp
> +            updateSizeBySizeMode();
看要不要改个名字，现在这个已经不是bysizemode了，之前起的名字不太好，

2023-04-19 08:22 UTC, 18202781743 commented on src/widgets/dmainwindow.cpp
> +    DConfig *uiPreferDonfig = new DConfig("org.deepin.dtk.ui.preference", "", this);
更新阴影位置，这里监听titlebar的高度变化是不是更好，
另外不用调用setFixedHeight,

2023-04-19 08:26 UTC, kegechen requested changes

2023-04-19 08:26 UTC, kegechen commented on src/widgets/dmainwindow.cpp
> +    });
这不是又监听了一边 dconfig 的变化吗.  还有 updateSizeBySizeMode 不是会setFixedHeight 吗?

只需要 dtitlebar 的 size 变化能在 dmainwindow 里面获取到然后更新就可以了.  可以看看这个 DEnhancedWidget

2023-04-19 08:33 UTC, chenchongbiao commented on src/widgets/dtitlebar.cpp
> +            updateSizeBySizeMode();
那updateTitleBarSize() 可以不

2023-04-19 08:52 UTC, chenchongbiao commented on src/widgets/dmainwindow.cpp
> +    });
好的 我看一下先。

2023-04-19 14:40 UTC, chenchongbiao commented on src/widgets/dmainwindow.cpp
> +    });
> updateSizeBySizeMode
虽然DTitleBar的私有类里监听了titlebarHeight，updateSizeBySizeMode里有setFixedHeight，但是在titlebarHeight修改时，DMainwindows中的updateTitleShadowGeometry的titlebar->geometry().bottom()获取到的是修改前的坐标。然后阴影的大小就变得奇怪了。

2023-04-20 02:20 UTC, zccrs requested changes

2023-04-20 02:20 UTC, zccrs commented on include/widgets/dtitlebar.h
> +    void heightChanged();
直接叫 sizeChanged()

2023-04-20 02:20 UTC, zccrs commented on src/widgets/dtitlebar.cpp
> +    if (event->type() == QEvent::Resize) {
监听自己的大小改变不应该走 eventFilter，重写 resizeEvent 就行了

2023-04-20 02:21 UTC, chenchongbiao commented on src/widgets/dtitlebar.cpp
> +    if (event->type() == QEvent::Resize) {
好

2023-04-20 02:21 UTC, chenchongbiao commented on include/widgets/dtitlebar.h
> +    void heightChanged();
我改一下

2023-04-20 03:26 UTC, kegechen commented
> **CLA Assistant Lite bot** All contributors have signed the CLA writing_hand white_check_mark

@chenchongbiao 有公司邮箱的话配置成公司邮箱

2023-04-20 03:27 UTC, kegechen reviewed
+1

2023-04-20 04:31 UTC, chenchongbiao commented
> > **CLA Assistant Lite bot** All contributors have signed the CLA writing_hand white_check_mark
> 
> @chenchongbiao 有公司邮箱的话配置成公司邮箱

改了。

2023-04-20 05:37 UTC, zccrs submitted a review, later dismissed

2023-04-20 06:30 UTC, kegechen commented
> 修复titlebarHeight属性被修改时，标题栏没有实时生效。
> 
> issue: [linuxdeepin/dtk#51](https://github.com/linuxdeepin/dtk/issues/51)

Issue: 大写( commit 规范里面有.

2023-04-20 08:46 UTC, zccrs approved these changes

2023-04-21 05:18 UTC, kegechen approved these changes

2023-04-26 05:14 UTC, merged