fix: TextEdit color group not update
linuxdeepin/dtkwidget pull request #450
Opened 2023-05-18 07:32 UTC by kegechen

control's palette not changed whene window activate changed

Bug: https://pms.uniontech.com/bug-view-196603.html

2023-05-18 07:33 UTC, kegechen commented
其实不是 DTextEdit 独有的问题， 使用 QTextEdit 也一样， 窗口失去焦点时， widget->palette->setCurrentColorGroup(QPalette::Inactive)  即控件调色板当前状态会改成 `inactive` , 而 `dtkgui` 对于 `inactive` 的颜色是会调整的，看起来就是略微变灰。QTextEdit 给 QWidgetTextControl 设置调色板后不会因为窗口激活改变而更新调色板

2023-05-18 07:54 UTC, zccrs commented
> 

这个意思是说 QWidgetTextControl 不会因为窗口的激活与否选择使用 Active 还是 Inative group 的颜色吗？

2023-05-18 08:27 UTC, kegechen commented
> > 
> 
> 这个意思是说 QWidgetTextControl 不会因为窗口的激活与否选择使用 Active 还是 Inative group 的颜色吗？

是的。主要是从控制中心修改活动色时应用的窗口是非激活的，活动色改变dtkgui会通知 qtgui palette 变化，qtextedit在这个事件会设置palette到control
```cpp
void QTextEdit::changeEvent(QEvent *e)
{
    Q_D(QTextEdit);
    QAbstractScrollArea::changeEvent(e);
    if (...)
    // ...
    } else if (e->type() == QEvent::PaletteChange) {
        d->control->setPalette(palette());
    } 
}

const QPalette &QWidget::palette() const
{
    if (!isEnabled()) {
        data->pal.setCurrentColorGroup(QPalette::Disabled);
    } else if ((!isVisible() || isActiveWindow())
#if defined(Q_OS_WIN) && !defined(Q_OS_WINRT)
        && !QApplicationPrivate::isBlockedByModal(const_cast<QWidget *>(this))
#endif
        ) {
        data->pal.setCurrentColorGroup(QPalette::Active);
    } else {
        data->pal.setCurrentColorGroup(QPalette::Inactive);
    }
    return data->pal;
}
```

2023-05-18 08:27 UTC, kegechen commented
应该可以给qtbase提一个pr修复

2023-05-18 09:00 UTC, zccrs requested changes

2023-05-18 09:00 UTC, zccrs commented on src/widgets/dtextedit.cpp
> +    } else if (e->type() == QEvent::WindowActivate ||
在这里加一下 workaround 说明，以及 TODO

2023-05-19 05:09 UTC, zccrs commented on src/widgets/dtextedit.cpp
> +               !DGuiApplicationHelper::testAttribute(DGuiApplicationHelper::UseInactiveColorGroup)) {
应该是非的关系吗，UseInactiveColorGroup 好像是指要不要用到 Inactive 颜色，如果没用到的话，是不是就用做下面的更新

2023-05-30 08:48 UTC, kegechen commented on src/widgets/dtextedit.cpp
> +               !DGuiApplicationHelper::testAttribute(DGuiApplicationHelper::UseInactiveColorGroup)) {
DGuiApplicationHelper::setAttribute(DGuiApplicationHelper::UseInactiveColorGroup, false);  // 不用
默认就是有个这个flag 的
https://github.com/linuxdeepin/dtkgui/blob/master/src/kernel/dguiapplicationhelper.cpp#LL187C70-L187C70

2023-06-16 05:51 UTC, kegechen commented
> 应该可以给qtbase提一个pr修复

https://codereview.qt-project.org/c/qt/qtbase/+/483056

2023-06-16 06:16 UTC, zccrs approved these changes

2023-06-16 08:15 UTC, merged