doc: update docs for dpasswordedit
linuxdeepin/dtkwidget pull request #468
Opened 2023-06-29 08:52 UTC by homehomehu

更新dpasswordedit的文档 #467 

Log: update docs

Task: deepin-community/coding-quarter#26

2023-06-30 02:31 UTC, homehomehu commented
> **CLA Assistant Lite bot:** **如果你是以企业贡献者的身份进行提交，请[联系我们](mailto: support@deepin.org)签署[企业贡献者许可协议](https://github.com/linuxdeepin/cla/blob/master/%E4%BC%81%E4%B8%9A%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%B8%E5%8F%AF%E5%8D%8F%E8%AE%AE%EF%BC%88%E4%B8%AD%E6%96%87%E7%89%88%EF%BC%89-V1.0.md)** **If you submit as corporate contributor, please [contact us](mailto: support@deepin.org) to sign our [Corporate Contributor License Agreement](https://github.com/linuxdeepin/cla/blob/master/Corporate%20Contributor%20License%20Agreement-EN-V1.0.md)** 感谢您的提交，我们非常感谢。 像许多开源项目一样，在接受您的贡献之前，我们要求您签署我们的[个人贡献者许可协议](https://github.com/linuxdeepin/cla/blob/master/%E4%B8%AA%E4%BA%BA%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%B8%E5%8F%AF%E5%8D%8F%E8%AE%AE%EF%BC%88%E4%B8%AD%E6%96%87%E7%89%88%EF%BC%89-V1.0.md)。 您只需发布与以下格式相同的评论即可签署[个人贡献者许可协议](https://github.com/linuxdeepin/cla/blob/master/%E4%B8%AA%E4%BA%BA%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%B8%E5%8F%AF%E5%8D%8F%E8%AE%AE%EF%BC%88%E4%B8%AD%E6%96%87%E7%89%88%EF%BC%89-V1.0.md)。 Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Individual Contributor License Agreement](https://github.com/linuxdeepin/cla/blob/master/Individual%20Contributor%20License%20Agreement-EN-V1.0.md) before we can accept your contribution. You can sign the [Individual Contributor License Agreement](https://github.com/linuxdeepin/cla/blob/master/Individual%20Contributor%20License%20Agreement-EN-V1.0.md) by just posting a Pull Request Comment same as the below format.
> 
> ```
> I have read the CLA Document and I hereby sign the CLA.
> ```
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I hereby sign the CLA.

2023-06-30 02:33 UTC, homehomehu commented
I have read the CLA Document and I hereby sign the CLA.

recheck

2023-06-30 02:34 UTC, homehomehu commented
I have read the CLA Document and I hereby sign the CLA.

2023-06-30 02:34 UTC, homehomehu commented
recheck

2023-06-30 02:45 UTC, asterwyx requested changes

2023-06-30 02:45 UTC, asterwyx commented on docs/widgets/dpasswordedit.zh_CN.dox
> +@brief DPasswordEdit::DPasswordEdit 实例化了一个DpasswordEdit.
```suggestion
@brief DPasswordEdit::DPasswordEdit 实例化了一个DPasswordEdit.
```

2023-06-30 02:45 UTC, asterwyx commented on docs/widgets/dpasswordedit.zh_CN.dox
> +@a 父部件被传递给DLineEdit构造函数.
doxygen的风格应该是@param吧

2023-06-30 02:45 UTC, asterwyx commented on docs/widgets/dpasswordedit.zh_CN.dox
> +@brief 设置显示模式
```suggestion
@brief 设置回显模式
```

2023-06-30 02:45 UTC, asterwyx commented on docs/widgets/dpasswordedit.zh_CN.dox
> +@brief 设置输入密码是否可见
这个应该是用来设置开关回显模式的按钮是否是可见的，输入密码是否可见由回显模式控制

2023-06-30 02:45 UTC, asterwyx commented on src/widgets/dpasswordedit.cpp
>    \inmodule dtkwidget
这个也要跟着改一下

2023-06-30 02:45 UTC, asterwyx commented on src/widgets/dpasswordedit.cpp
> +  @a mode
@param

2023-06-30 02:45 UTC, asterwyx commented on src/widgets/dpasswordedit.cpp
> +  @a "visible true" means the input password is visible, while "visible false" means the input password is not visible.
同上

2023-06-30 05:34 UTC, xzl01 reviewed
需要添加截图示例

2023-06-30 05:47 UTC, asterwyx commented on src/widgets/dpasswordedit.cpp
> +  @param "visible true" means the input password is visible, while "visible false" means the input password is not visible.
```suggestion
  @param visible "true" means the input password is visible, while "false" means the input password is not visible.
```

2023-06-30 05:47 UTC, asterwyx commented on src/widgets/dpasswordedit.cpp
> +  @param "visible true" means the input password is visible, while "visible false" means the input password is not visible.
@param \<variable\> \<description\>是固定格式

2023-06-30 07:30 UTC, homehomehu commented
recheck

2023-06-30 08:24 UTC, xzl01 submitted a review, later dismissed

2023-06-30 09:12 UTC, asterwyx commented on src/widgets/dpasswordedit.cpp
> +  @param visible "true" means the input password is visible, while "false" means the input password is not visible.
这个地方和上面的文档一样要改一下，是改变回显模式的按钮是否可见

2023-07-03 00:59 UTC, kegechen commented on docs/widgets/dpasswordedit.zh_CN.dox
> +@return true输入密码可见,false不可见
这个函数的意思是控件是否可见吧，不是输入的密码是否可见，是不是和 isEchoMode 搞混淆了

2023-07-03 01:00 UTC, kegechen commented on src/widgets/dpasswordedit.cpp
> +  @return If "true", the input password is visible. If "false", the input password is not visible.
原注释就是错误，不要将错就错啊

2023-07-03 02:31 UTC, xzl01 commented
@param[in]  我们要求参数区分传入参数和传出参数

2023-07-03 06:19 UTC, xzl01 commented on docs/widgets/dpasswordedit.zh_CN.dox
> +<img src="/data/home/homehome/workspace/dtkwidget/docs/images/dpasswordedit_example2.png" alt="Example 2" width="700" height="370">
使用相对路径 否则这个图片只能在你的电脑上可见

2023-07-03 07:21 UTC, xzl01 commented on .gitignore
> +docs/doxygen-theme/
尾部需要空行

2023-07-03 07:30 UTC, kegechen commented
commit msg 再参考commit规范改一下

2023-07-03 07:41 UTC, homehomehu commented
> commit msg 再参考commit规范改一下

2023-07-03 08:47 UTC, xzl01 approved these changes

2023-07-03 08:47 UTC, asterwyx approved these changes

2023-07-03 08:58 UTC, homehomehu commented
/merge

2023-07-03 08:59 UTC, merged