doc: update docs for dbaseexpand
linuxdeepin/dtkwidget pull request #474
Opened 2023-07-04 09:12 UTC by lavender9527

更新dbaseexpand的文档

Log: update docs

Issue: linuxdeepin/dtk #94

2023-07-04 09:41 UTC, xzl01 commented on docs/widgets/dbaseexpand.zh_CN.dox
> +\inmodule dtkwidget
doxygen应该不支持这个命令

2023-07-04 09:42 UTC, xzl01 commented on docs/widgets/dbaseexpand.zh_CN.dox
> +*/
结尾需要有一个空行

2023-07-05 01:20 UTC, lavender9527 commented
recheck

2023-07-05 02:01 UTC, xzl01 commented on docs/widgets/dbaseexpand.zh_CN.dox
> +@image html DBaseExpand.gif
这个引用的图片为啥是gif？

2023-07-05 02:43 UTC, asterwyx requested changes

2023-07-05 02:43 UTC, asterwyx commented on src/widgets/dbaseexpand.cpp
> +  @brief A beautiful expandable control.
```suggestion
  @brief A beautiful expandable widget.
```

2023-07-05 02:43 UTC, asterwyx commented on src/widgets/dbaseexpand.cpp
> +  Using the DBaseExpand class, you can create a controllable control with an animation effect. This control contains the upper and lower parts. The above control is the title control. This control wi
```suggestion
  Using the DBaseExpand class, you can create a expandable control with an animation effect. This control contains the upper and lower parts. The above control is the title control. This control will always display Call dbaseexpand :: setexpand to set the visibility of the content control. Use dbaseexpand :: setHeader and dbaseexpand :: SetContent to set the title control and content control respectively.
```

2023-07-05 02:43 UTC, asterwyx commented on src/widgets/dbaseexpand.cpp
> +  Using the DBaseExpand class, you can create a controllable control with an animation effect. This control contains the upper and lower parts. The above control is the title control. This control wi
control的错误同上

2023-07-05 02:43 UTC, asterwyx commented on src/widgets/dbaseexpand.cpp
> +  Content control is hidden by default, call dbaseexpand :: setexpand to set its visibility.
这里的冒号看起来不太对劲

2023-07-05 02:43 UTC, asterwyx commented on src/widgets/dbaseexpand.cpp
> +  @brief set the time for the visibility of the content control
这里用duration更好，是一个时间段而不是time

2023-07-05 03:24 UTC, asterwyx approved these changes

2023-07-06 04:31 UTC, lavender9527 commented
/merge

2023-07-06 04:32 UTC, merged