doc: update docs for dwaterprogress
linuxdeepin/dtkwidget pull request #475
Opened 2023-07-04 09:37 UTC by homehomehu

更新dwaterprogress的文档

Log: update docs

Task: deepin-community/coding-quarter#26

2023-07-04 09:41 UTC, xzl01 commented on docs/widgets/dwaterprogress.zh_CN.dox
> +### demo示例
建议加一些调用的代码展示

2023-07-05 02:52 UTC, asterwyx requested changes

2023-07-05 02:52 UTC, asterwyx commented on docs/widgets/dwaterprogress.zh_CN.dox
> +    DWaterProgress waterProgress(&window);
最好只有顶层窗口是静态的，其他控件都是new出来挂到顶层窗口的控件树上，这样写容易出现内存问题。

2023-07-05 02:52 UTC, asterwyx commented on docs/widgets/dwaterprogress.zh_CN.dox
> +    QVBoxLayout layout(&window);
同上

2023-07-05 02:52 UTC, asterwyx commented on docs/widgets/dwaterprogress.zh_CN.dox
> +可见，给出了进度条的一种趣味展示形式，作用是可以减少用户枯燥的等待（比如此处格式化的等待），主要用在小工具主窗口内部
减少等待这个再斟酌一下

2023-07-05 02:52 UTC, asterwyx commented on docs/widgets/dwaterprogress.zh_CN.dox
> +@brief 设置是否显示进度
```suggestion
@brief 设置是否显示进度文字
```

2023-07-05 03:21 UTC, xzl01 commented on docs/images/dwaterprogress.png
图片不需要做更改的

2023-07-05 03:32 UTC, homehomehu commented on docs/images/dwaterprogress.png
但是和docs目录下readme里运行后所展示的控件图片不一致，也不需要更改吗

2023-07-05 08:19 UTC, homehomehu commented on docs/images/dwaterprogress.png
已经更换成自己的示例demo图片

2023-07-05 08:27 UTC, asterwyx approved these changes

2023-07-05 08:38 UTC, kegechen commented on docs/widgets/dwaterprogress.zh_CN.dox
> +    QDate today = QDate::currentDate();
和当前无关的代码尽量去掉，减少干扰

2023-07-06 02:04 UTC, asterwyx requested changes

2023-07-06 02:04 UTC, asterwyx commented on src/widgets/dwaterprogress.cpp
> +    @brief Use DWaterProgress to create an new water animation progress.
```suggestion
    @brief Use DWaterProgress to create a new water animation progress.
```

2023-07-06 02:04 UTC, asterwyx commented on src/widgets/dwaterprogress.cpp
> -    \inmodule dtkwidget
这个应该也有对应的doxygen风格的注解，看看docs目录下定义了哪些module，然后确定这个文件位于哪个module

2023-07-06 02:19 UTC, homehomehu commented on src/widgets/dwaterprogress.cpp
> -    \inmodule dtkwidget
在cpp文件里写@inmodule无法被识别为合法的标签。且在文档网页上会原封不动显示@inmodule，我试了是这样的

2023-07-06 02:54 UTC, asterwyx commented on src/widgets/dwaterprogress.cpp
> -    \inmodule dtkwidget
@ingroup 用这个

2023-07-06 03:31 UTC, asterwyx approved these changes

2023-07-06 03:45 UTC, homehomehu commented
/merge

2023-07-06 03:59 UTC, homehomehu commented
/merge

2023-07-06 03:59 UTC, merged