doc: update docs for dcircleprogress
linuxdeepin/dtkwidget pull request #483
Opened 2023-07-07 03:00 UTC by homehomehu

更新dcircleprogress的文档

Log: update docs

Issue: https://github.com/linuxdeepin/dtk/issues/94

2023-07-10 02:10 UTC, kegechen commented on docs/widgets/dcircleprogress.zh_CN.dox
> +    circleProgress->setLineWidth(30);
这个没必要这么宽吧。不太好看

2023-07-10 02:12 UTC, kegechen commented on src/widgets/dcircleprogress.cpp
> +  Maximum value is 100, minimum value is 0.
这个接口应该有个bug,  可以改一下示例，看看会不会修复，单独加一个修复的提交就很好了

2023-07-10 07:21 UTC, kegechen requested changes

2023-07-10 07:21 UTC, kegechen commented on docs/widgets/dcircleprogress.zh_CN.dox
> +    timer->start(100);  // 设置定时器的超时时间，每 100 ms 增加一点进度
这个start的参数貌似不是说的时间间隔，而是100ms之后开启timer. 时间间隔需要单独设置

2023-07-10 07:21 UTC, kegechen commented on src/widgets/dcircleprogress.cpp
> +    }
单独一个提交，不要混在一起

可以这样写
```
if (d->m_currentValue == value)
  return;
```
 注释删掉

2023-07-10 07:58 UTC, homehomehu commented on src/widgets/dcircleprogress.cpp
> +    }
已新交了一个commit（chore: update interface bug for dcircleprogress

2023-07-10 08:24 UTC, kegechen commented on docs/widgets/dcircleprogress.zh_CN.dox
> +    });
这个不要放在这个提交吧。

2023-07-10 08:27 UTC, kegechen requested changes
chore: update interface bug for dcircleprogress
太笼统了。

修复bug的是 fix; 可以具体到描述你修复了什么问题
如 修复了 valuechanged 从来不会发射的问题

2023-07-10 08:33 UTC, homehomehu commented
> chore: update interface bug for dcircleprogress 太笼统了。
> 
> 修复bug的是 fix; 可以具体到描述你修复了什么问题 如 修复了 valuechanged 从来不会发射的问题

已经更改~

2023-07-10 08:36 UTC, kegechen commented on docs/widgets/dcircleprogress.zh_CN.dox
> +    });
文档就不要分裂成俩提交吧。先修复bug的提交, 然后更新文档的基于这个修复bug的提交一次改完就可以了

2023-07-10 08:53 UTC, homehomehu commented on docs/widgets/dcircleprogress.zh_CN.dox
> +    });
我现在是等这个bug的被merge了之后再开个pr更新文档对吧？有点子懵

2023-07-11 05:21 UTC, kegechen approved these changes

2023-07-11 06:37 UTC, merged