fix: 在控制中心-vpn界面点击导出后，保存后，vpn界面依然置灰
linuxdeepin/dtkwidget pull request #535
Opened 2023-11-08 08:52 UTC by LiHua000

Log: DApplication应用初始化时设置了xcb窗口属性，导致收不到部分事件，正常情况下关闭文件选择对话框后，会收到两次FocusIn事件，一次来自底层，一次来自其他客户端，而应用中收不到其他客户端发的FocusIn事件，添加事件掩码后即可。

Bug: https://pms.uniontech.com/bug-view-220369.html

2023-11-09 01:56 UTC, zccrs requested changes

2023-11-09 01:56 UTC, zccrs commented on src/widgets/private/startupnotifications/startupnotificationmonitor.cpp
> +    const uint32_t select_input_val[] = { XCB_EVENT_MASK_PROPERTY_CHANGE | XCB_EVENT_MASK_BUTTON_PRESS };
这里的想法应该只是希望增加对 XCB_EVENT_MASK_PROPERTY_CHANGE 的关注，但是实际情况是覆盖了原有的 XCB_CW_EVENT_MASK。可以尝试改成在原有的 XCB_CW_EVENT_MASK 值的基础上加上 XCB_EVENT_MASK_PROPERTY_CHANGE，这样或许能解决问题。

2023-11-09 03:47 UTC, LiHua000 commented on src/widgets/private/startupnotifications/startupnotificationmonitor.cpp
> +    const uint32_t select_input_val[] = { XCB_EVENT_MASK_PROPERTY_CHANGE | XCB_EVENT_MASK_BUTTON_PRESS };
done

2023-11-09 05:17 UTC, zccrs requested changes

2023-11-09 05:17 UTC, zccrs commented on src/widgets/private/startupnotifications/startupnotificationmonitor.cpp
> +    uint32_t old_event_mask = attr_reply->your_event_mask;
attr_reply可能为空，在使用前需要判断。

2023-11-09 05:17 UTC, zccrs commented on src/widgets/private/startupnotifications/startupnotificationmonitor.cpp
> +    uint32_t old_event_mask = attr_reply->your_event_mask;
另外在使用后需要销毁它

2023-11-09 06:32 UTC, zccrs submitted a review, later dismissed

2023-11-09 06:46 UTC, LiHua000 commented
/merge

2023-11-09 06:56 UTC, kegechen commented
/check obs

2023-11-10 08:52 UTC, kegechen commented
/check obs

2023-11-13 05:43 UTC, asterwyx commented
commit信息主体前面的尾注Log删一下

2023-11-13 07:07 UTC, kegechen approved these changes

2023-11-13 07:10 UTC, merged