fix: Split window position error
linuxdeepin/dtkwidget pull request #564
Opened 2024-04-11 10:46 UTC by mhduiy

Move to inside the screen when exceeding the edge of the screen

Issue: https://github.com/linuxdeepin/developer-center/issues/4840

2024-04-11 10:47 UTC, mhduiy commented
修改后效果图
![image](https://github.com/linuxdeepin/dtkwidget/assets/73688594/22aef74f-d551-49f2-97d5-ceae56ab50e3)

2024-04-12 01:50 UTC, kegechen approved these changes

2024-04-12 01:50 UTC, kegechen commented on src/widgets/dtitlebar.cpp
> +
空行--

2024-04-12 01:51 UTC, kegechen requested changes

2024-04-12 01:51 UTC, kegechen commented on src/widgets/dtitlebar.cpp
> +
--

2024-04-12 01:57 UTC, kegechen approved these changes

2024-04-12 02:08 UTC, merged