fix: 修复大多数按钮不响应enter事件
linuxdeepin/dtkwidget pull request #569
Opened 2024-05-07 06:57 UTC by kegechen

修复大多数按钮不响应enter事件,仅支持DApplication应用

Log: 修复大多数按钮不响应enter事件
Bug: https://pms.uniontech.com/bug-view-253935.html
Influence: 按钮响应键盘回车事件

2024-05-07 06:59 UTC, kegechen commented on src/widgets/dapplication.cpp
> +#if QT_VERSION < QT_VERSION_CHECK(6, 4, 0)
qt 6不需要处理 @FeiWang1119 已经处理过了
- https://github.com/linuxdeepin/qt5integration/pull/207

2024-05-07 06:59 UTC, kegechen commented
@Whale107

2024-05-08 10:15 UTC, zccrs requested changes

2024-05-08 10:15 UTC, zccrs commented on src/widgets/dapplication.cpp
> +#if QT_VERSION < QT_VERSION_CHECK(6, 4, 0)
意思是从 Qt 6.4.0 开始可以依赖 qt5integration 里的实现了？但是我看那个提交里并没有判断是 >= Qt 6.4.0 呀。
另外，这里最好是加上注释说明下判断这个版本的依据。

2024-05-09 01:57 UTC, kegechen commented on src/widgets/dapplication.cpp
> +#if QT_VERSION < QT_VERSION_CHECK(6, 4, 0)
那个提交版本判断写低了 :)

2024-05-09 02:17 UTC, kegechen commented
use QPlatformTheme::ButtonPressKeys for pressing buttons

https://codereview.qt-project.org/c/qt/qtbase/+/394849

2024-05-09 02:37 UTC, zccrs approved these changes

2024-05-09 06:55 UTC, kegechen commented
/retest

2024-05-09 08:16 UTC, kegechen commented
/retest

2024-05-09 08:55 UTC, kegechen commented
/forcemerge

2024-05-09 08:55 UTC, merged