chore: 新增进度条动效和一个新进度条类
linuxdeepin/dtkwidget pull request #589
Opened 2024-07-18 09:56 UTC by Whale107

新增进度条动效和一个新进度条类

Log:

2024-07-23 02:12 UTC, Whale107 commented
I have read the CLA Document and I hereby sign the CLA.

2024-07-31 08:54 UTC, kegechen commented on src/widgets/dindeterminateprogressbar.cpp
> +// SPDX-FileCopyrightText: 2019 - 2024 UnionTech Software Technology Co., Ltd.
```suggestion
// SPDX-FileCopyrightText:  2024 UnionTech Software Technology Co., Ltd.
```

2019  就有这个类了？ 其他同上

2024-07-31 10:09 UTC, zccrs requested changes

2024-07-31 10:09 UTC, zccrs commented on include/widgets/dindeterminateprogressbar.h
> +// SPDX-FileCopyrightText: 2019 - 2024 UnionTech Software Technology Co., Ltd.
这个文件是2019年创建的？

2024-07-31 10:09 UTC, zccrs commented on src/widgets/dtitlebar.cpp
>              delete leftLayout->takeAt(0);
是不是改成 delete speacerItem 就行了？

2024-07-31 10:09 UTC, zccrs commented on src/widgets/dprogressbar.cpp
> +void DProgressBar::paintEvent(QPaintEvent *e)
为什么要覆盖进度条的paint？Qt的控件要在 style 插件中实现样式和动画。只有dtk的原生控件才考虑在dtkwidget里实现。

2024-08-01 12:27 UTC, zccrs commented on include/widgets/dindeterminateprogressbar.h
> +class DIndeterminateProgressbarPrivate;
需要添加dtk widget的namespace

2024-08-01 12:28 UTC, zccrs commented on src/widgets/dindeterminateprogressbar.cpp
> +    this->height() <= DTK_WIDGET_NAMESPACE::DStyle::pixelMetric(style(), DTK_WIDGET_NAMESPACE::DStyle::PM_FrameRadius) * 2
当类在namespace中定义后不需要在中这个宏

2024-08-01 12:29 UTC, zccrs commented on include/widgets/dindeterminateprogressbar.h
> +class DIndeterminateProgressbar : public QWidget, public DTK_CORE_NAMESPACE::DObject
LIBDTKWIDGETSHARED_EXPORT

2024-08-01 13:24 UTC, zccrs requested changes

2024-08-01 13:24 UTC, zccrs commented on src/widgets/dindeterminateprogressbar.cpp
> +const int SPOT_WIDGET_WIDTH = 200;
constexpr

2024-08-01 13:24 UTC, zccrs commented on include/widgets/dindeterminateprogressbar.h
> +    int sliderWidth();
为了适应未来可能会添加竖直方向布局，这里不应该用 width，可以用size

2024-08-02 05:35 UTC, kegechen reviewed
在example中的progressbar加一个展示

2024-08-02 05:42 UTC, kegechen requested changes
无关提交去掉

2024-08-02 05:49 UTC, kegechen commented on src/widgets/dindeterminateprogressbar.cpp
> +    d->m_sliderWidget->setFixedWidth(150);
这个不应该固定把，是不是一个比例。 比如控件长度的 1/3...1/4...1/5，和设计对一下

2024-08-02 05:58 UTC, kegechen commented on src/widgets/dindeterminateprogressbar.cpp
> +    return {width(), 20};
高度也固定？ 和设计对一下

2024-08-02 05:59 UTC, kegechen commented on src/widgets/dindeterminateprogressbar.cpp
> +    if (d->m_sliderWidget->width() == size)
不能超过自己的宽度吧

2024-08-02 07:35 UTC, kegechen reviewed
+1

2024-08-02 07:48 UTC, merged