add :/translations in loadTranslator path
linuxdeepin/dtkwidget pull request #81
Opened 2021-06-11 10:03 UTC by wangling12

Because the store strictly limits the installation path of third-party applications. Adding this path may simplify third-party application development.

2021-06-23 03:28 UTC, kegechen reviewed
Add DTK_STATIC_TRANSLATION=YES to add support for static translations

try DTK_STATIC_TRANSLATION ?

2021-06-29 03:25 UTC, wangling12 commented
> Add DTK_STATIC_TRANSLATION=YES to add support for static translations
> 
> try DTK_STATIC_TRANSLATION ?


这个宏未打开，默认情况下无法使用应用无法使用，或许可以和以下修复一起，默认打开该功能？
linuxdeepin/dtkcommon#1

2022-03-16 02:08 UTC, zccrs requested changes
I'm sorry to reply to you now, we have migrated the dtkcommon project to github for development, thank you for the PR, but it needs to be rebase to be merged, can you do it?

2023-01-18 03:41 UTC, asterwyx commented
请按照我合并的commit rebase代码, 并且合并成一个提交, 重新触发ci.

2023-01-18 07:13 UTC, wangling12 commented
还有人在看呢啊，是不是我是唯一一个在看这个的

> 请按照我合并的commit rebase代码, 并且合并成一个提交, 重新触发ci.

rebase了，之前提交这个是因为试图用dtk开发并上架商店的话，翻译文件根本没地方放置。不确定这个问题是否依旧存在。。。 😂😂

2023-01-18 09:30 UTC, asterwyx commented on debian/rules
> +	dh_auto_configure -- -DBUILD_PLUGINS=OFF -DBUILD_DOCS=OFF -DVERSION=$(_PACK_VER) DTK_STATIC_TRANSLATION=YES
```suggestion
	dh_auto_configure -- -DBUILD_PLUGINS=OFF -DBUILD_DOCS=OFF -DVERSION=$(_PACK_VER) -DDTK_STATIC_TRANSLATION=YES
```

2023-01-18 09:33 UTC, asterwyx commented
> 还有人在看呢啊，是不是我是唯一一个在看这个的
> 
> > 请按照我合并的commit rebase代码, 并且合并成一个提交, 重新触发ci.
> 
> rebase了，之前提交这个是因为试图用dtk开发并上架商店的话，翻译文件根本没地方放置。不确定这个问题是否依旧存在。。。 joyjoy

静态翻译功能代码里面还是存在的,这个PR可以合并.我近期在处理dtkwidget的重构,顺便清理一下旧的PR.

2023-01-18 09:34 UTC, asterwyx commented on debian/rules
> +	dh_auto_configure -- -DBUILD_PLUGINS=OFF -DBUILD_DOCS=OFF -DVERSION=$(_PACK_VER) DTK_STATIC_TRANSLATION=YES
dtkwidget已经全面换成cmake配置的方式了,这里给cmake传参的话前面要加上-D

2023-01-18 10:11 UTC, zccrs approved these changes

2023-01-31 03:42 UTC, wangling12 commented on debian/rules
> +	dh_auto_configure -- -DBUILD_PLUGINS=OFF -DBUILD_DOCS=OFF -DVERSION=$(_PACK_VER) DTK_STATIC_TRANSLATION=YES
DONE

2023-01-31 05:48 UTC, asterwyx submitted a review, later dismissed

2023-07-05 01:34 UTC, hudeng-go commented
/check build-deb

2023-10-16 02:53 UTC, kegechen commented
approved了多次，又冲突了。approved 之后及时 merge（回复 `/merge` 即可） @wangling12

2023-10-17 02:54 UTC, wangling12 commented
/merge

2023-10-17 02:56 UTC, wangling12 commented
哥，这个自动化流程好高端 :rofl: :rofl:

2023-10-17 07:44 UTC, asterwyx commented
> 哥，这个自动化流程好高端 🤣 🤣

签一下CLA吧，回复/recheck

2023-10-17 07:47 UTC, asterwyx submitted a review, later dismissed
请签署CLA。

2023-10-17 07:49 UTC, asterwyx commented
好像rebase还有问题，先手动rebase一下吧，只留一个commit。

2023-10-19 02:22 UTC, wangling12 commented
/recheck

2023-10-19 02:44 UTC, asterwyx approved these changes

2023-10-19 02:45 UTC, merged