fix: wayland DArrowRectangle mouse propagation
linuxdeepin/dtkwidget pull request #89
Opened 2022-03-15 09:58 UTC by kegechen

wayland 下绘制透明的区域没有鼠标穿透导致无法点击后面的控件。
如果 handle 无效，则使用 qwidget::setmask

Bug: https://pms.uniontech.com/bug-view-99340.html
Influence: wayland-DArrowRectangle-dde-calendar
Change-Id: I0ce66452e443acf88cd3b5b72514ed3bff3a8bd2

2022-03-16 03:23 UTC, zccrs requested changes

2022-03-16 03:23 UTC, zccrs commented on src/widgets/darrowrectangle.cpp
> +        q->setShadowBlurRadius(2); // 没有handle就减小 shadow, 防止 mask 之后 show 的位置偏移
没有handle时不会有shadow吧？

2022-03-16 03:23 UTC, zccrs commented on src/widgets/darrowrectangle.cpp
> +        QPolygon polygon = path.united(copy).toFillPolygon().toPolygon();
这是想让path向外放大1px吗？用这种融合的方式，在右上角和左下角应该会有问题，可以用 QPainterPathStroker 处理

2022-03-16 07:53 UTC, kegechen commented on src/widgets/darrowrectangle.cpp
> +        q->setShadowBlurRadius(2); // 没有handle就减小 shadow, 防止 mask 之后 show 的位置偏移
有 DGraphicsGlowEffect 这个会加一层shadow

![image](https://user-images.githubusercontent.com/23466548/158542031-49783d86-d298-425f-9268-c3ea22c8851e.png)

2022-03-16 07:55 UTC, kegechen commented on src/widgets/darrowrectangle.cpp
> +        QPolygon polygon = path.united(copy).toFillPolygon().toPolygon();
是的外扩1像素，我看下 QPainterPathStroker 用法

2022-03-17 05:48 UTC, zccrs requested changes

2022-03-17 05:48 UTC, zccrs commented on src/widgets/darrowrectangle.cpp
> +//        DGraphicsGlowEffect *glowEffect = new DGraphicsGlowEffect;
不用注释掉，真的不需要的话就直接删掉

2022-03-17 05:55 UTC, zccrs approved these changes

2022-03-17 06:00 UTC, kegechen commented on src/widgets/darrowrectangle.cpp
> +//        DGraphicsGlowEffect *glowEffect = new DGraphicsGlowEffect;
done

2022-03-17 06:00 UTC, merged