chore: dtkwidget csd without dxcb
linuxdeepin/dtkwidget pull request #99
Opened 2022-04-14 09:24 UTC by kegechen

1. setWindowFlag Qt::FramelessWindowHint
2. call startSystemMove when mouse move with left button pressed
3. always show dtitlebar buttons

Log: 
Incluence: notitlebar without dxcb plugin
Change-Id: I57caa33f56306540fd62e8e7bf13d59a7ad46cee

2022-04-14 09:25 UTC, kegechen commented
加了接口，谨慎合并。

2022-06-01 03:29 UTC, zccrs requested changes
这个是要解决啥问题呢，什么情况下会 without dxcb？
另外，这里只处理了窗口的 move，没有处理 resize

2022-06-14 05:49 UTC, kegechen commented
> 这个是要解决啥问题呢，什么情况下会 without dxcb？ 另外，这里只处理了窗口的 move，没有处理 resize

resize窗管会处理，这里解决在没有dxcb（notitlebar）的情况下，依然使用自绘标题栏，只是没有圆角而已，且标题栏支持拖动窗口。

2023-02-14 08:10 UTC, kegechen commented
csd 需要满足两点：
1. 只需要 dtkdui 的 enablenotitlebar 为 true.  通知 窗管 不需要为当前应用绘制 ssd
2. 有move 和 resize的接口供 dtkwidget 调用

2023-02-15 03:31 UTC, zccrs commented
> > 这个是要解决啥问题呢，什么情况下会 without dxcb？ 另外，这里只处理了窗口的 move，没有处理 resize
> 
> resize窗管会处理，这里解决在没有dxcb（notitlebar）的情况下，依然使用自绘标题栏，只是没有圆角而已，且标题栏支持拖动窗口。

这个确定吗，自绘标题里的情况下（未使用窗管的标题里），窗管应该是不会接管这个窗口的resize。

2023-02-16 06:02 UTC, kegechen commented
> 

确实不管。

2023-10-09 01:20 UTC, closed without merging